veille_technologiqueveille_homepage:
    path:     /hello/{name}
    defaults: { _controller: veilleTechnologiqueveilleBundle:Default:index }

_home:
  resource: "@veilleTechnologiqueveilleBundle/Controller/DefaultController.php"
  type: annotation
  prefix: /

_user:
  resource: "@veilleTechnologiqueveilleBundle/Controller/UserController.php"
  type: annotation
  prefix: /user/
