parameters:
#    veille_technologiqueveille.example.class: veilleTechnologique\veilleBundle\Example

services:
#    veille_technologiqueveille.example:
#        class: %veille_technologiqueveille.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
